//action types as string constants

export const ADD_SHOP = 'ADD_SHOP';
export const ADD_SHOP_PENDING = 'ADD_SHOP_PENDING';
export const ADD_SHOP_FULFILLED = 'ADD_SHOP_FULFILLED';

export const FETCH_SHOPS = 'FETCH_SHOPS';
export const FETCH_SHOPS_PENDING = 'FETCH_SHOPS_PENDING';
export const FETCH_SHOPS_FULFILLED = 'FETCH_SHOPS_FULFILLED';

export const ADD_VIEWPOINT = 'ADD_VIEWPOINT';
export const ADD_VIEWPOINT_PENDING = 'ADD_VIEWPOINT_PENDING';
export const ADD_VIEWPOINT_FULFILLED = 'ADD_VIEWPOINT_FULFILLED';