//action types as string constants

//SHOPS
export const ADD_SHOP = 'ADD_SHOP';
export const ADD_SHOP_PENDING = 'ADD_SHOP_PENDING';
export const ADD_SHOP_FULFILLED = 'ADD_SHOP_FULFILLED';

export const FETCH_SHOPS = 'FETCH_SHOPS';
export const FETCH_SHOPS_PENDING = 'FETCH_SHOPS_PENDING';
export const FETCH_SHOPS_FULFILLED = 'FETCH_SHOPS_FULFILLED';

export const EDIT_SHOP = 'EDIT_SHOP';
export const EDIT_SHOP_PENDING = 'EDIT_SHOP_PENDING';
export const EDIT_SHOP_FULFILLED = 'EDIT_SHOP_FULFILLED';

export const DELETE_SHOP = 'DELETE_SHOP';
export const DELETE_SHOP_PENDING = 'DELETE_SHOP_PENDING';
export const DELETE_SHOP_FULFILLED = 'DELETE_SHOP_FULFILLED';

//VIEWPOINTS
export const ADD_VIEWPOINT = 'ADD_VIEWPOINT';
export const ADD_VIEWPOINT_PENDING = 'ADD_VIEWPOINT_PENDING';
export const ADD_VIEWPOINT_FULFILLED = 'ADD_VIEWPOINT_FULFILLED';

export const FETCH_VIEWPOINTS = 'FETCH_VIEWPOINTS';
export const FETCH_VIEWPOINTS_PENDING = 'FETCH_VIEWPOINTS_PENDING';
export const FETCH_VIEWPOINTS_FULFILLED = 'FETCH_VIEWPOINTS_FULFILLED';

export const CLEAR_VIEWPOINTS = 'CLEAR_VIEWPOINTS';

//PRODUCTS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING';
export const ADD_PRODUCT_FULFILLED = 'ADD_PRODUCT_FULFILLED';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_PENDING = 'EDIT_PRODUCT_PENDING';
export const EDIT_PRODUCT_FULFILLED = 'EDIT_PRODUCT_FULFILLED';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_FULFILLED = 'FETCH_PRODUCTS_FULFILLED';

export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_FULFILLED = 'DELETE_PRODUCT_FULFILLED';

//HOTSPOTS
export const ADD_HOTSPOT = 'ADD_HOTSPOT';
export const ADD_HOTSPOT_PENDING = 'ADD_HOTSPOT_PENDING';
export const ADD_HOTSPOT_FULFILLED = 'ADD_HOTSPOT_FULFILLED';

export const DELETE_HOTSPOT = 'DELETE_HOTSPOT';
export const DELETE_HOTSPOT_PENDING = 'DELETE_HOTSPOT_PENDING';
export const DELETE_HOTSPOT_FULFILLED = 'DELETE_HOTSPOT_FULFILLED';


export const CLEAR_HOTSPOTS = 'CLEAR_HOTSPOTS';

export const CONNECT_PRODUCT_TO_HOTSPOT = 'CONNECT_PRODUCT_TO_HOTSPOT';
export const CONNECT_PRODUCT_TO_HOTSPOT_PENDING = 'CONNECT_PRODUCT_TO_HOTSPOT_PENDING';
export const CONNECT_PRODUCT_TO_HOTSPOT_FULFILLED = 'CONNECT_PRODUCT_TO_HOTSPOT_FULFILLED';

export const FETCH_HOTSPOTS = 'FETCH_HOTSPOTS';
export const FETCH_HOTSPOTS_PENDING = 'FETCH_HOTSPOTS_PENDING';
export const FETCH_HOTSPOTS_FULFILLED = 'FETCH_HOTSPOTS_FULFILLED';

//CATEGORIES
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED'; 